site_name: ProfileService
site_url: https://madstudioroblox.github.io/ProfileService
repo_name: MadStudioRoblox/ProfileService
repo_url: https://github.com/MadStudioRoblox/ProfileService

theme:
  name: material
  palette:
    primary: "Deep Purple"
    accent: "Deep Purple"

nav:
  - Home: docs/index.md
  - Tutorial:
    - Setting up: docs/tutorial/settingup.md
    - Basic Usage: docs/tutorial/basic_usage.md
  - API: docs/api.md

markdown_extensions:
  - admonition
  - codehilite